module Cookie
  class Error < StandardError
  end

  class UnauthorizedError < Error
  end

  class AuthenticationError < Error
  end

  class ApiError < Error
  end

  class Client
    BASE_URL: String

    @api_key: String?
    @connection: Faraday::Connection?
    @login: Resources::Login?
    @orders: Resources::Orders?

    attr_reader adapter: Symbol

    def self.authenticate: (username: String, credential: String) -> Client
    def initialize: (?api_key: String?, ?adapter: Symbol) -> void
    def setup_authorization: (String) -> void
    def connection: () -> Faraday::Connection

    def login: () -> Resources::Login
    def orders: () -> Resources::Orders
  end
end
